/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoScheduleRouteImport } from './routes/demo/schedule'
import { Route as DemoContactRouteImport } from './routes/demo/contact'
import { Route as DemoAboutRouteImport } from './routes/demo/about'
import { Route as DemoServicesIndexRouteImport } from './routes/demo/services.index'
import { Route as DemoSectorsIndexRouteImport } from './routes/demo/sectors.index'
import { Route as DemoProjectsIndexRouteImport } from './routes/demo/projects.index'
import { Route as DemoGalleryIndexRouteImport } from './routes/demo/gallery.index'
import { Route as DemoCareersIndexRouteImport } from './routes/demo/careers.index'
import { Route as DemoBlogsIndexRouteImport } from './routes/demo/blogs.index'
import { Route as DashboardVacanciesIndexRouteImport } from './routes/dashboard/vacancies/index'
import { Route as DashboardServicesIndexRouteImport } from './routes/dashboard/services/index'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardGalleryIndexRouteImport } from './routes/dashboard/gallery/index'
import { Route as DashboardBusinessSectorsIndexRouteImport } from './routes/dashboard/business-sectors/index'
import { Route as DashboardBlogsIndexRouteImport } from './routes/dashboard/blogs/index'
import { Route as DemoServicesSlugRouteImport } from './routes/demo/services.$slug'
import { Route as DemoSectorsSlugRouteImport } from './routes/demo/sectors.$slug'
import { Route as DemoProjectsSlugRouteImport } from './routes/demo/projects.$slug'
import { Route as DemoCareersSlugRouteImport } from './routes/demo/careers.$slug'
import { Route as DemoBlogsSlugRouteImport } from './routes/demo/blogs.$slug'
import { Route as DashboardServicesCreateRouteImport } from './routes/dashboard/services/create'
import { Route as DashboardGalleryCategoriesRouteImport } from './routes/dashboard/gallery/categories'
import { Route as DashboardBusinessSectorsCreateRouteImport } from './routes/dashboard/business-sectors/create'
import { Route as DashboardVacanciesSlugIndexRouteImport } from './routes/dashboard/vacancies/$slug/index'
import { Route as DashboardUserManagementUserIdIndexRouteImport } from './routes/dashboard/user-management/$userId/index'
import { Route as DashboardTestimonialsIdIndexRouteImport } from './routes/dashboard/testimonials/$id/index'
import { Route as DashboardServicesSlugIndexRouteImport } from './routes/dashboard/services/$slug/index'
import { Route as DashboardProductsSlugIndexRouteImport } from './routes/dashboard/products/$slug/index'
import { Route as DashboardPartnersIdIndexRouteImport } from './routes/dashboard/partners/$id/index'
import { Route as DashboardGalleryIdIndexRouteImport } from './routes/dashboard/gallery/$id/index'
import { Route as DashboardContactUsIdIndexRouteImport } from './routes/dashboard/contact-us/$id/index'
import { Route as DashboardClientProjectsSlugIndexRouteImport } from './routes/dashboard/client-projects/$slug/index'
import { Route as DashboardBusinessSectorsSlugIndexRouteImport } from './routes/dashboard/business-sectors/$slug/index'
import { Route as DashboardBlogsSlugIndexRouteImport } from './routes/dashboard/blogs/$slug/index'
import { Route as DashboardVacanciesSlugEditRouteImport } from './routes/dashboard/vacancies/$slug/edit'
import { Route as DashboardVacanciesSlugApplicationsRouteImport } from './routes/dashboard/vacancies/$slug/applications'
import { Route as DashboardUserManagementUserIdEditRouteImport } from './routes/dashboard/user-management/$userId/edit'
import { Route as DashboardTestimonialsIdEditRouteImport } from './routes/dashboard/testimonials/$id/edit'
import { Route as DashboardServicesSlugEditRouteImport } from './routes/dashboard/services/$slug/edit'
import { Route as DashboardProductsSlugEditRouteImport } from './routes/dashboard/products/$slug/edit'
import { Route as DashboardPartnersIdEditRouteImport } from './routes/dashboard/partners/$id/edit'
import { Route as DashboardGalleryIdEditRouteImport } from './routes/dashboard/gallery/$id/edit'
import { Route as DashboardContactUsIdEditRouteImport } from './routes/dashboard/contact-us/$id/edit'
import { Route as DashboardClientProjectsSlugEditRouteImport } from './routes/dashboard/client-projects/$slug/edit'
import { Route as DashboardBusinessSectorsSlugEditRouteImport } from './routes/dashboard/business-sectors/$slug/edit'
import { Route as DashboardBlogsSlugEditRouteImport } from './routes/dashboard/blogs/$slug/edit'

const RegisterLazyRouteImport = createFileRoute('/register')()
const RateLimitLazyRouteImport = createFileRoute('/rate-limit')()
const LoginLazyRouteImport = createFileRoute('/login')()
const ForbiddenLazyRouteImport = createFileRoute('/forbidden')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardUserManagementIndexLazyRouteImport = createFileRoute(
  '/dashboard/user-management/',
)()
const DashboardTestimonialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/',
)()
const DashboardTagsIndexLazyRouteImport = createFileRoute('/dashboard/tags/')()
const DashboardSocialsIndexLazyRouteImport = createFileRoute(
  '/dashboard/socials/',
)()
const DashboardPartnersIndexLazyRouteImport = createFileRoute(
  '/dashboard/partners/',
)()
const DashboardOrganizationalStructureIndexLazyRouteImport = createFileRoute(
  '/dashboard/organizational-structure/',
)()
const DashboardFaqsIndexLazyRouteImport = createFileRoute('/dashboard/faqs/')()
const DashboardContactUsIndexLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/',
)()
const DashboardClientProjectsIndexLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/',
)()
const DashboardVacanciesCreateLazyRouteImport = createFileRoute(
  '/dashboard/vacancies/create',
)()
const DashboardUserManagementCreateLazyRouteImport = createFileRoute(
  '/dashboard/user-management/create',
)()
const DashboardTestimonialsCreateLazyRouteImport = createFileRoute(
  '/dashboard/testimonials/create',
)()
const DashboardProductsCreateLazyRouteImport = createFileRoute(
  '/dashboard/products/create',
)()
const DashboardPartnersCreateLazyRouteImport = createFileRoute(
  '/dashboard/partners/create',
)()
const DashboardGalleryCreateLazyRouteImport = createFileRoute(
  '/dashboard/gallery/create',
)()
const DashboardContactUsCreateLazyRouteImport = createFileRoute(
  '/dashboard/contact-us/create',
)()
const DashboardClientProjectsCreateLazyRouteImport = createFileRoute(
  '/dashboard/client-projects/create',
)()
const DashboardBlogsCreateLazyRouteImport = createFileRoute(
  '/dashboard/blogs/create',
)()

const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const RateLimitLazyRoute = RateLimitLazyRouteImport.update({
  id: '/rate-limit',
  path: '/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/rate-limit.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForbiddenLazyRoute = ForbiddenLazyRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/forbidden.lazy').then((d) => d.Route))
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() => import('./routes/demo/index.lazy').then((d) => d.Route))
const DemoScheduleRoute = DemoScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DemoRoute,
} as any).lazy(() => import('./routes/demo/schedule.lazy').then((d) => d.Route))
const DemoContactRoute = DemoContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => DemoRoute,
} as any).lazy(() => import('./routes/demo/contact.lazy').then((d) => d.Route))
const DemoAboutRoute = DemoAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DemoRoute,
} as any).lazy(() => import('./routes/demo/about.lazy').then((d) => d.Route))
const DashboardUserManagementIndexLazyRoute =
  DashboardUserManagementIndexLazyRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIndexLazyRoute =
  DashboardTestimonialsIndexLazyRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/index.lazy').then((d) => d.Route),
  )
const DashboardTagsIndexLazyRoute = DashboardTagsIndexLazyRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/tags/index.lazy').then((d) => d.Route),
)
const DashboardSocialsIndexLazyRoute =
  DashboardSocialsIndexLazyRouteImport.update({
    id: '/socials/',
    path: '/socials/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/socials/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIndexLazyRoute =
  DashboardPartnersIndexLazyRouteImport.update({
    id: '/partners/',
    path: '/partners/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/index.lazy').then((d) => d.Route),
  )
const DashboardOrganizationalStructureIndexLazyRoute =
  DashboardOrganizationalStructureIndexLazyRouteImport.update({
    id: '/organizational-structure/',
    path: '/organizational-structure/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/organizational-structure/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardFaqsIndexLazyRoute = DashboardFaqsIndexLazyRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/faqs/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIndexLazyRoute =
  DashboardContactUsIndexLazyRouteImport.update({
    id: '/contact-us/',
    path: '/contact-us/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsIndexLazyRoute =
  DashboardClientProjectsIndexLazyRouteImport.update({
    id: '/client-projects/',
    path: '/client-projects/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DemoServicesIndexRoute = DemoServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/services.index.lazy').then((d) => d.Route),
)
const DemoSectorsIndexRoute = DemoSectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/sectors.index.lazy').then((d) => d.Route),
)
const DemoProjectsIndexRoute = DemoProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/projects.index.lazy').then((d) => d.Route),
)
const DemoGalleryIndexRoute = DemoGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/gallery.index.lazy').then((d) => d.Route),
)
const DemoCareersIndexRoute = DemoCareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/careers.index.lazy').then((d) => d.Route),
)
const DemoBlogsIndexRoute = DemoBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/blogs.index.lazy').then((d) => d.Route),
)
const DashboardVacanciesIndexRoute = DashboardVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/vacancies/index.lazy').then((d) => d.Route),
)
const DashboardServicesIndexRoute = DashboardServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/index.lazy').then((d) => d.Route),
)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/products/index.lazy').then((d) => d.Route),
)
const DashboardGalleryIndexRoute = DashboardGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/index.lazy').then((d) => d.Route),
)
const DashboardBusinessSectorsIndexRoute =
  DashboardBusinessSectorsIndexRouteImport.update({
    id: '/business-sectors/',
    path: '/business-sectors/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsIndexRoute = DashboardBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/index.lazy').then((d) => d.Route),
)
const DashboardVacanciesCreateLazyRoute =
  DashboardVacanciesCreateLazyRouteImport.update({
    id: '/vacancies/create',
    path: '/vacancies/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/create.lazy').then((d) => d.Route),
  )
const DashboardUserManagementCreateLazyRoute =
  DashboardUserManagementCreateLazyRouteImport.update({
    id: '/user-management/create',
    path: '/user-management/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsCreateLazyRoute =
  DashboardTestimonialsCreateLazyRouteImport.update({
    id: '/testimonials/create',
    path: '/testimonials/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/create.lazy').then((d) => d.Route),
  )
const DashboardProductsCreateLazyRoute =
  DashboardProductsCreateLazyRouteImport.update({
    id: '/products/create',
    path: '/products/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/create.lazy').then((d) => d.Route),
  )
const DashboardPartnersCreateLazyRoute =
  DashboardPartnersCreateLazyRouteImport.update({
    id: '/partners/create',
    path: '/partners/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/create.lazy').then((d) => d.Route),
  )
const DashboardGalleryCreateLazyRoute =
  DashboardGalleryCreateLazyRouteImport.update({
    id: '/gallery/create',
    path: '/gallery/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/create.lazy').then((d) => d.Route),
  )
const DashboardContactUsCreateLazyRoute =
  DashboardContactUsCreateLazyRouteImport.update({
    id: '/contact-us/create',
    path: '/contact-us/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/create.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsCreateLazyRoute =
  DashboardClientProjectsCreateLazyRouteImport.update({
    id: '/client-projects/create',
    path: '/client-projects/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsCreateLazyRoute =
  DashboardBlogsCreateLazyRouteImport.update({
    id: '/blogs/create',
    path: '/blogs/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/blogs/create.lazy').then((d) => d.Route),
  )
const DemoServicesSlugRoute = DemoServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/services.$slug.lazy').then((d) => d.Route),
)
const DemoSectorsSlugRoute = DemoSectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/sectors.$slug.lazy').then((d) => d.Route),
)
const DemoProjectsSlugRoute = DemoProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/projects.$slug.lazy').then((d) => d.Route),
)
const DemoCareersSlugRoute = DemoCareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/careers.$slug.lazy').then((d) => d.Route),
)
const DemoBlogsSlugRoute = DemoBlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => DemoRoute,
} as any).lazy(() =>
  import('./routes/demo/blogs.$slug.lazy').then((d) => d.Route),
)
const DashboardServicesCreateRoute = DashboardServicesCreateRouteImport.update({
  id: '/services/create',
  path: '/services/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/services/create.lazy').then((d) => d.Route),
)
const DashboardGalleryCategoriesRoute =
  DashboardGalleryCategoriesRouteImport.update({
    id: '/gallery/categories',
    path: '/gallery/categories',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/gallery/categories.lazy').then((d) => d.Route),
  )
const DashboardBusinessSectorsCreateRoute =
  DashboardBusinessSectorsCreateRouteImport.update({
    id: '/business-sectors/create',
    path: '/business-sectors/create',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/create.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardVacanciesSlugIndexRoute =
  DashboardVacanciesSlugIndexRouteImport.update({
    id: '/vacancies/$slug/',
    path: '/vacancies/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdIndexRoute =
  DashboardUserManagementUserIdIndexRouteImport.update({
    id: '/user-management/$userId/',
    path: '/user-management/$userId/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdIndexRoute =
  DashboardTestimonialsIdIndexRouteImport.update({
    id: '/testimonials/$id/',
    path: '/testimonials/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugIndexRoute =
  DashboardServicesSlugIndexRouteImport.update({
    id: '/services/$slug/',
    path: '/services/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugIndexRoute =
  DashboardProductsSlugIndexRouteImport.update({
    id: '/products/$slug/',
    path: '/products/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/index.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdIndexRoute =
  DashboardPartnersIdIndexRouteImport.update({
    id: '/partners/$id/',
    path: '/partners/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/partners/$id/index.lazy').then((d) => d.Route),
  )
const DashboardGalleryIdIndexRoute = DashboardGalleryIdIndexRouteImport.update({
  id: '/gallery/$id/',
  path: '/gallery/$id/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/index.lazy').then((d) => d.Route),
)
const DashboardContactUsIdIndexRoute =
  DashboardContactUsIdIndexRouteImport.update({
    id: '/contact-us/$id/',
    path: '/contact-us/$id/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/index.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugIndexRoute =
  DashboardClientProjectsSlugIndexRouteImport.update({
    id: '/client-projects/$slug/',
    path: '/client-projects/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugIndexRoute =
  DashboardBusinessSectorsSlugIndexRouteImport.update({
    id: '/business-sectors/$slug/',
    path: '/business-sectors/$slug/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugIndexRoute = DashboardBlogsSlugIndexRouteImport.update({
  id: '/blogs/$slug/',
  path: '/blogs/$slug/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/index.lazy').then((d) => d.Route),
)
const DashboardVacanciesSlugEditRoute =
  DashboardVacanciesSlugEditRouteImport.update({
    id: '/vacancies/$slug/edit',
    path: '/vacancies/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardVacanciesSlugApplicationsRoute =
  DashboardVacanciesSlugApplicationsRouteImport.update({
    id: '/vacancies/$slug/applications',
    path: '/vacancies/$slug/applications',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/vacancies/$slug/applications.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardUserManagementUserIdEditRoute =
  DashboardUserManagementUserIdEditRouteImport.update({
    id: '/user-management/$userId/edit',
    path: '/user-management/$userId/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/user-management/$userId/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardTestimonialsIdEditRoute =
  DashboardTestimonialsIdEditRouteImport.update({
    id: '/testimonials/$id/edit',
    path: '/testimonials/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/testimonials/$id/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardServicesSlugEditRoute =
  DashboardServicesSlugEditRouteImport.update({
    id: '/services/$slug/edit',
    path: '/services/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/services/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardProductsSlugEditRoute =
  DashboardProductsSlugEditRouteImport.update({
    id: '/products/$slug/edit',
    path: '/products/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/$slug/edit.lazy').then((d) => d.Route),
  )
const DashboardPartnersIdEditRoute = DashboardPartnersIdEditRouteImport.update({
  id: '/partners/$id/edit',
  path: '/partners/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/partners/$id/edit.lazy').then((d) => d.Route),
)
const DashboardGalleryIdEditRoute = DashboardGalleryIdEditRouteImport.update({
  id: '/gallery/$id/edit',
  path: '/gallery/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/gallery/$id/edit.lazy').then((d) => d.Route),
)
const DashboardContactUsIdEditRoute =
  DashboardContactUsIdEditRouteImport.update({
    id: '/contact-us/$id/edit',
    path: '/contact-us/$id/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contact-us/$id/edit.lazy').then((d) => d.Route),
  )
const DashboardClientProjectsSlugEditRoute =
  DashboardClientProjectsSlugEditRouteImport.update({
    id: '/client-projects/$slug/edit',
    path: '/client-projects/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/client-projects/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBusinessSectorsSlugEditRoute =
  DashboardBusinessSectorsSlugEditRouteImport.update({
    id: '/business-sectors/$slug/edit',
    path: '/business-sectors/$slug/edit',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/business-sectors/$slug/edit.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardBlogsSlugEditRoute = DashboardBlogsSlugEditRouteImport.update({
  id: '/blogs/$slug/edit',
  path: '/blogs/$slug/edit',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/blogs/$slug/edit.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/contact': typeof DemoContactRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/demo/blogs/$slug': typeof DemoBlogsSlugRoute
  '/demo/careers/$slug': typeof DemoCareersSlugRoute
  '/demo/projects/$slug': typeof DemoProjectsSlugRoute
  '/demo/sectors/$slug': typeof DemoSectorsSlugRoute
  '/demo/services/$slug': typeof DemoServicesSlugRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/demo/blogs': typeof DemoBlogsIndexRoute
  '/demo/careers': typeof DemoCareersIndexRoute
  '/demo/gallery': typeof DemoGalleryIndexRoute
  '/demo/projects': typeof DemoProjectsIndexRoute
  '/demo/sectors': typeof DemoSectorsIndexRoute
  '/demo/services': typeof DemoServicesIndexRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/contact': typeof DemoContactRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo': typeof DemoIndexRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/demo/blogs/$slug': typeof DemoBlogsSlugRoute
  '/demo/careers/$slug': typeof DemoCareersSlugRoute
  '/demo/projects/$slug': typeof DemoProjectsSlugRoute
  '/demo/sectors/$slug': typeof DemoSectorsSlugRoute
  '/demo/services/$slug': typeof DemoServicesSlugRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery': typeof DashboardGalleryIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
  '/dashboard/services': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies': typeof DashboardVacanciesIndexRoute
  '/demo/blogs': typeof DemoBlogsIndexRoute
  '/demo/careers': typeof DemoCareersIndexRoute
  '/demo/gallery': typeof DemoGalleryIndexRoute
  '/demo/projects': typeof DemoProjectsIndexRoute
  '/demo/sectors': typeof DemoSectorsIndexRoute
  '/demo/services': typeof DemoServicesIndexRoute
  '/dashboard/client-projects': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/forbidden': typeof ForbiddenLazyRoute
  '/login': typeof LoginLazyRoute
  '/rate-limit': typeof RateLimitLazyRoute
  '/register': typeof RegisterLazyRoute
  '/demo/about': typeof DemoAboutRoute
  '/demo/contact': typeof DemoContactRoute
  '/demo/schedule': typeof DemoScheduleRoute
  '/demo/': typeof DemoIndexRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/business-sectors/create': typeof DashboardBusinessSectorsCreateRoute
  '/dashboard/gallery/categories': typeof DashboardGalleryCategoriesRoute
  '/dashboard/services/create': typeof DashboardServicesCreateRoute
  '/demo/blogs/$slug': typeof DemoBlogsSlugRoute
  '/demo/careers/$slug': typeof DemoCareersSlugRoute
  '/demo/projects/$slug': typeof DemoProjectsSlugRoute
  '/demo/sectors/$slug': typeof DemoSectorsSlugRoute
  '/demo/services/$slug': typeof DemoServicesSlugRoute
  '/dashboard/blogs/create': typeof DashboardBlogsCreateLazyRoute
  '/dashboard/client-projects/create': typeof DashboardClientProjectsCreateLazyRoute
  '/dashboard/contact-us/create': typeof DashboardContactUsCreateLazyRoute
  '/dashboard/gallery/create': typeof DashboardGalleryCreateLazyRoute
  '/dashboard/partners/create': typeof DashboardPartnersCreateLazyRoute
  '/dashboard/products/create': typeof DashboardProductsCreateLazyRoute
  '/dashboard/testimonials/create': typeof DashboardTestimonialsCreateLazyRoute
  '/dashboard/user-management/create': typeof DashboardUserManagementCreateLazyRoute
  '/dashboard/vacancies/create': typeof DashboardVacanciesCreateLazyRoute
  '/dashboard/blogs/': typeof DashboardBlogsIndexRoute
  '/dashboard/business-sectors/': typeof DashboardBusinessSectorsIndexRoute
  '/dashboard/gallery/': typeof DashboardGalleryIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
  '/dashboard/services/': typeof DashboardServicesIndexRoute
  '/dashboard/vacancies/': typeof DashboardVacanciesIndexRoute
  '/demo/blogs/': typeof DemoBlogsIndexRoute
  '/demo/careers/': typeof DemoCareersIndexRoute
  '/demo/gallery/': typeof DemoGalleryIndexRoute
  '/demo/projects/': typeof DemoProjectsIndexRoute
  '/demo/sectors/': typeof DemoSectorsIndexRoute
  '/demo/services/': typeof DemoServicesIndexRoute
  '/dashboard/client-projects/': typeof DashboardClientProjectsIndexLazyRoute
  '/dashboard/contact-us/': typeof DashboardContactUsIndexLazyRoute
  '/dashboard/faqs/': typeof DashboardFaqsIndexLazyRoute
  '/dashboard/organizational-structure/': typeof DashboardOrganizationalStructureIndexLazyRoute
  '/dashboard/partners/': typeof DashboardPartnersIndexLazyRoute
  '/dashboard/socials/': typeof DashboardSocialsIndexLazyRoute
  '/dashboard/tags/': typeof DashboardTagsIndexLazyRoute
  '/dashboard/testimonials/': typeof DashboardTestimonialsIndexLazyRoute
  '/dashboard/user-management/': typeof DashboardUserManagementIndexLazyRoute
  '/dashboard/blogs/$slug/edit': typeof DashboardBlogsSlugEditRoute
  '/dashboard/business-sectors/$slug/edit': typeof DashboardBusinessSectorsSlugEditRoute
  '/dashboard/client-projects/$slug/edit': typeof DashboardClientProjectsSlugEditRoute
  '/dashboard/contact-us/$id/edit': typeof DashboardContactUsIdEditRoute
  '/dashboard/gallery/$id/edit': typeof DashboardGalleryIdEditRoute
  '/dashboard/partners/$id/edit': typeof DashboardPartnersIdEditRoute
  '/dashboard/products/$slug/edit': typeof DashboardProductsSlugEditRoute
  '/dashboard/services/$slug/edit': typeof DashboardServicesSlugEditRoute
  '/dashboard/testimonials/$id/edit': typeof DashboardTestimonialsIdEditRoute
  '/dashboard/user-management/$userId/edit': typeof DashboardUserManagementUserIdEditRoute
  '/dashboard/vacancies/$slug/applications': typeof DashboardVacanciesSlugApplicationsRoute
  '/dashboard/vacancies/$slug/edit': typeof DashboardVacanciesSlugEditRoute
  '/dashboard/blogs/$slug/': typeof DashboardBlogsSlugIndexRoute
  '/dashboard/business-sectors/$slug/': typeof DashboardBusinessSectorsSlugIndexRoute
  '/dashboard/client-projects/$slug/': typeof DashboardClientProjectsSlugIndexRoute
  '/dashboard/contact-us/$id/': typeof DashboardContactUsIdIndexRoute
  '/dashboard/gallery/$id/': typeof DashboardGalleryIdIndexRoute
  '/dashboard/partners/$id/': typeof DashboardPartnersIdIndexRoute
  '/dashboard/products/$slug/': typeof DashboardProductsSlugIndexRoute
  '/dashboard/services/$slug/': typeof DashboardServicesSlugIndexRoute
  '/dashboard/testimonials/$id/': typeof DashboardTestimonialsIdIndexRoute
  '/dashboard/user-management/$userId/': typeof DashboardUserManagementUserIdIndexRoute
  '/dashboard/vacancies/$slug/': typeof DashboardVacanciesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/demo/about'
    | '/demo/contact'
    | '/demo/schedule'
    | '/demo/'
    | '/dashboard/'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/demo/blogs/$slug'
    | '/demo/careers/$slug'
    | '/demo/projects/$slug'
    | '/demo/sectors/$slug'
    | '/demo/services/$slug'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/demo/blogs'
    | '/demo/careers'
    | '/demo/gallery'
    | '/demo/projects'
    | '/demo/sectors'
    | '/demo/services'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/demo/about'
    | '/demo/contact'
    | '/demo/schedule'
    | '/demo'
    | '/dashboard'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/demo/blogs/$slug'
    | '/demo/careers/$slug'
    | '/demo/projects/$slug'
    | '/demo/sectors/$slug'
    | '/demo/services/$slug'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs'
    | '/dashboard/business-sectors'
    | '/dashboard/gallery'
    | '/dashboard/products'
    | '/dashboard/services'
    | '/dashboard/vacancies'
    | '/demo/blogs'
    | '/demo/careers'
    | '/demo/gallery'
    | '/demo/projects'
    | '/demo/sectors'
    | '/demo/services'
    | '/dashboard/client-projects'
    | '/dashboard/contact-us'
    | '/dashboard/faqs'
    | '/dashboard/organizational-structure'
    | '/dashboard/partners'
    | '/dashboard/socials'
    | '/dashboard/tags'
    | '/dashboard/testimonials'
    | '/dashboard/user-management'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug'
    | '/dashboard/business-sectors/$slug'
    | '/dashboard/client-projects/$slug'
    | '/dashboard/contact-us/$id'
    | '/dashboard/gallery/$id'
    | '/dashboard/partners/$id'
    | '/dashboard/products/$slug'
    | '/dashboard/services/$slug'
    | '/dashboard/testimonials/$id'
    | '/dashboard/user-management/$userId'
    | '/dashboard/vacancies/$slug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/forbidden'
    | '/login'
    | '/rate-limit'
    | '/register'
    | '/demo/about'
    | '/demo/contact'
    | '/demo/schedule'
    | '/demo/'
    | '/dashboard/'
    | '/dashboard/business-sectors/create'
    | '/dashboard/gallery/categories'
    | '/dashboard/services/create'
    | '/demo/blogs/$slug'
    | '/demo/careers/$slug'
    | '/demo/projects/$slug'
    | '/demo/sectors/$slug'
    | '/demo/services/$slug'
    | '/dashboard/blogs/create'
    | '/dashboard/client-projects/create'
    | '/dashboard/contact-us/create'
    | '/dashboard/gallery/create'
    | '/dashboard/partners/create'
    | '/dashboard/products/create'
    | '/dashboard/testimonials/create'
    | '/dashboard/user-management/create'
    | '/dashboard/vacancies/create'
    | '/dashboard/blogs/'
    | '/dashboard/business-sectors/'
    | '/dashboard/gallery/'
    | '/dashboard/products/'
    | '/dashboard/services/'
    | '/dashboard/vacancies/'
    | '/demo/blogs/'
    | '/demo/careers/'
    | '/demo/gallery/'
    | '/demo/projects/'
    | '/demo/sectors/'
    | '/demo/services/'
    | '/dashboard/client-projects/'
    | '/dashboard/contact-us/'
    | '/dashboard/faqs/'
    | '/dashboard/organizational-structure/'
    | '/dashboard/partners/'
    | '/dashboard/socials/'
    | '/dashboard/tags/'
    | '/dashboard/testimonials/'
    | '/dashboard/user-management/'
    | '/dashboard/blogs/$slug/edit'
    | '/dashboard/business-sectors/$slug/edit'
    | '/dashboard/client-projects/$slug/edit'
    | '/dashboard/contact-us/$id/edit'
    | '/dashboard/gallery/$id/edit'
    | '/dashboard/partners/$id/edit'
    | '/dashboard/products/$slug/edit'
    | '/dashboard/services/$slug/edit'
    | '/dashboard/testimonials/$id/edit'
    | '/dashboard/user-management/$userId/edit'
    | '/dashboard/vacancies/$slug/applications'
    | '/dashboard/vacancies/$slug/edit'
    | '/dashboard/blogs/$slug/'
    | '/dashboard/business-sectors/$slug/'
    | '/dashboard/client-projects/$slug/'
    | '/dashboard/contact-us/$id/'
    | '/dashboard/gallery/$id/'
    | '/dashboard/partners/$id/'
    | '/dashboard/products/$slug/'
    | '/dashboard/services/$slug/'
    | '/dashboard/testimonials/$id/'
    | '/dashboard/user-management/$userId/'
    | '/dashboard/vacancies/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  ForbiddenLazyRoute: typeof ForbiddenLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RateLimitLazyRoute: typeof RateLimitLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-limit': {
      id: '/rate-limit'
      path: '/rate-limit'
      fullPath: '/rate-limit'
      preLoaderRoute: typeof RateLimitLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/schedule': {
      id: '/demo/schedule'
      path: '/schedule'
      fullPath: '/demo/schedule'
      preLoaderRoute: typeof DemoScheduleRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/contact': {
      id: '/demo/contact'
      path: '/contact'
      fullPath: '/demo/contact'
      preLoaderRoute: typeof DemoContactRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/about': {
      id: '/demo/about'
      path: '/about'
      fullPath: '/demo/about'
      preLoaderRoute: typeof DemoAboutRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/user-management/': {
      id: '/dashboard/user-management/'
      path: '/user-management'
      fullPath: '/dashboard/user-management'
      preLoaderRoute: typeof DashboardUserManagementIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/': {
      id: '/dashboard/testimonials/'
      path: '/testimonials'
      fullPath: '/dashboard/testimonials'
      preLoaderRoute: typeof DashboardTestimonialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags/': {
      id: '/dashboard/tags/'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/socials/': {
      id: '/dashboard/socials/'
      path: '/socials'
      fullPath: '/dashboard/socials'
      preLoaderRoute: typeof DashboardSocialsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/': {
      id: '/dashboard/partners/'
      path: '/partners'
      fullPath: '/dashboard/partners'
      preLoaderRoute: typeof DashboardPartnersIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/organizational-structure/': {
      id: '/dashboard/organizational-structure/'
      path: '/organizational-structure'
      fullPath: '/dashboard/organizational-structure'
      preLoaderRoute: typeof DashboardOrganizationalStructureIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/faqs/': {
      id: '/dashboard/faqs/'
      path: '/faqs'
      fullPath: '/dashboard/faqs'
      preLoaderRoute: typeof DashboardFaqsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/': {
      id: '/dashboard/contact-us/'
      path: '/contact-us'
      fullPath: '/dashboard/contact-us'
      preLoaderRoute: typeof DashboardContactUsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/': {
      id: '/dashboard/client-projects/'
      path: '/client-projects'
      fullPath: '/dashboard/client-projects'
      preLoaderRoute: typeof DashboardClientProjectsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/services/': {
      id: '/demo/services/'
      path: '/services'
      fullPath: '/demo/services'
      preLoaderRoute: typeof DemoServicesIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/sectors/': {
      id: '/demo/sectors/'
      path: '/sectors'
      fullPath: '/demo/sectors'
      preLoaderRoute: typeof DemoSectorsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/projects/': {
      id: '/demo/projects/'
      path: '/projects'
      fullPath: '/demo/projects'
      preLoaderRoute: typeof DemoProjectsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/gallery/': {
      id: '/demo/gallery/'
      path: '/gallery'
      fullPath: '/demo/gallery'
      preLoaderRoute: typeof DemoGalleryIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/careers/': {
      id: '/demo/careers/'
      path: '/careers'
      fullPath: '/demo/careers'
      preLoaderRoute: typeof DemoCareersIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/blogs/': {
      id: '/demo/blogs/'
      path: '/blogs'
      fullPath: '/demo/blogs'
      preLoaderRoute: typeof DemoBlogsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/vacancies/': {
      id: '/dashboard/vacancies/'
      path: '/vacancies'
      fullPath: '/dashboard/vacancies'
      preLoaderRoute: typeof DashboardVacanciesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/': {
      id: '/dashboard/services/'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/': {
      id: '/dashboard/gallery/'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/': {
      id: '/dashboard/business-sectors/'
      path: '/business-sectors'
      fullPath: '/dashboard/business-sectors'
      preLoaderRoute: typeof DashboardBusinessSectorsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/': {
      id: '/dashboard/blogs/'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/create': {
      id: '/dashboard/vacancies/create'
      path: '/vacancies/create'
      fullPath: '/dashboard/vacancies/create'
      preLoaderRoute: typeof DashboardVacanciesCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/create': {
      id: '/dashboard/user-management/create'
      path: '/user-management/create'
      fullPath: '/dashboard/user-management/create'
      preLoaderRoute: typeof DashboardUserManagementCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/create': {
      id: '/dashboard/testimonials/create'
      path: '/testimonials/create'
      fullPath: '/dashboard/testimonials/create'
      preLoaderRoute: typeof DashboardTestimonialsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/create': {
      id: '/dashboard/products/create'
      path: '/products/create'
      fullPath: '/dashboard/products/create'
      preLoaderRoute: typeof DashboardProductsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/create': {
      id: '/dashboard/partners/create'
      path: '/partners/create'
      fullPath: '/dashboard/partners/create'
      preLoaderRoute: typeof DashboardPartnersCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/create': {
      id: '/dashboard/gallery/create'
      path: '/gallery/create'
      fullPath: '/dashboard/gallery/create'
      preLoaderRoute: typeof DashboardGalleryCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/create': {
      id: '/dashboard/contact-us/create'
      path: '/contact-us/create'
      fullPath: '/dashboard/contact-us/create'
      preLoaderRoute: typeof DashboardContactUsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/create': {
      id: '/dashboard/client-projects/create'
      path: '/client-projects/create'
      fullPath: '/dashboard/client-projects/create'
      preLoaderRoute: typeof DashboardClientProjectsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/create': {
      id: '/dashboard/blogs/create'
      path: '/blogs/create'
      fullPath: '/dashboard/blogs/create'
      preLoaderRoute: typeof DashboardBlogsCreateLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/services/$slug': {
      id: '/demo/services/$slug'
      path: '/services/$slug'
      fullPath: '/demo/services/$slug'
      preLoaderRoute: typeof DemoServicesSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/sectors/$slug': {
      id: '/demo/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/demo/sectors/$slug'
      preLoaderRoute: typeof DemoSectorsSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/projects/$slug': {
      id: '/demo/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/demo/projects/$slug'
      preLoaderRoute: typeof DemoProjectsSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/careers/$slug': {
      id: '/demo/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/demo/careers/$slug'
      preLoaderRoute: typeof DemoCareersSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/blogs/$slug': {
      id: '/demo/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/demo/blogs/$slug'
      preLoaderRoute: typeof DemoBlogsSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/dashboard/services/create': {
      id: '/dashboard/services/create'
      path: '/services/create'
      fullPath: '/dashboard/services/create'
      preLoaderRoute: typeof DashboardServicesCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/categories': {
      id: '/dashboard/gallery/categories'
      path: '/gallery/categories'
      fullPath: '/dashboard/gallery/categories'
      preLoaderRoute: typeof DashboardGalleryCategoriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/create': {
      id: '/dashboard/business-sectors/create'
      path: '/business-sectors/create'
      fullPath: '/dashboard/business-sectors/create'
      preLoaderRoute: typeof DashboardBusinessSectorsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/': {
      id: '/dashboard/vacancies/$slug/'
      path: '/vacancies/$slug'
      fullPath: '/dashboard/vacancies/$slug'
      preLoaderRoute: typeof DashboardVacanciesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/': {
      id: '/dashboard/user-management/$userId/'
      path: '/user-management/$userId'
      fullPath: '/dashboard/user-management/$userId'
      preLoaderRoute: typeof DashboardUserManagementUserIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/': {
      id: '/dashboard/testimonials/$id/'
      path: '/testimonials/$id'
      fullPath: '/dashboard/testimonials/$id'
      preLoaderRoute: typeof DashboardTestimonialsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/': {
      id: '/dashboard/services/$slug/'
      path: '/services/$slug'
      fullPath: '/dashboard/services/$slug'
      preLoaderRoute: typeof DashboardServicesSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/': {
      id: '/dashboard/products/$slug/'
      path: '/products/$slug'
      fullPath: '/dashboard/products/$slug'
      preLoaderRoute: typeof DashboardProductsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/': {
      id: '/dashboard/partners/$id/'
      path: '/partners/$id'
      fullPath: '/dashboard/partners/$id'
      preLoaderRoute: typeof DashboardPartnersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/': {
      id: '/dashboard/gallery/$id/'
      path: '/gallery/$id'
      fullPath: '/dashboard/gallery/$id'
      preLoaderRoute: typeof DashboardGalleryIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/': {
      id: '/dashboard/contact-us/$id/'
      path: '/contact-us/$id'
      fullPath: '/dashboard/contact-us/$id'
      preLoaderRoute: typeof DashboardContactUsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/': {
      id: '/dashboard/client-projects/$slug/'
      path: '/client-projects/$slug'
      fullPath: '/dashboard/client-projects/$slug'
      preLoaderRoute: typeof DashboardClientProjectsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/': {
      id: '/dashboard/business-sectors/$slug/'
      path: '/business-sectors/$slug'
      fullPath: '/dashboard/business-sectors/$slug'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/': {
      id: '/dashboard/blogs/$slug/'
      path: '/blogs/$slug'
      fullPath: '/dashboard/blogs/$slug'
      preLoaderRoute: typeof DashboardBlogsSlugIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/edit': {
      id: '/dashboard/vacancies/$slug/edit'
      path: '/vacancies/$slug/edit'
      fullPath: '/dashboard/vacancies/$slug/edit'
      preLoaderRoute: typeof DashboardVacanciesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vacancies/$slug/applications': {
      id: '/dashboard/vacancies/$slug/applications'
      path: '/vacancies/$slug/applications'
      fullPath: '/dashboard/vacancies/$slug/applications'
      preLoaderRoute: typeof DashboardVacanciesSlugApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/user-management/$userId/edit': {
      id: '/dashboard/user-management/$userId/edit'
      path: '/user-management/$userId/edit'
      fullPath: '/dashboard/user-management/$userId/edit'
      preLoaderRoute: typeof DashboardUserManagementUserIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/testimonials/$id/edit': {
      id: '/dashboard/testimonials/$id/edit'
      path: '/testimonials/$id/edit'
      fullPath: '/dashboard/testimonials/$id/edit'
      preLoaderRoute: typeof DashboardTestimonialsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services/$slug/edit': {
      id: '/dashboard/services/$slug/edit'
      path: '/services/$slug/edit'
      fullPath: '/dashboard/services/$slug/edit'
      preLoaderRoute: typeof DashboardServicesSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$slug/edit': {
      id: '/dashboard/products/$slug/edit'
      path: '/products/$slug/edit'
      fullPath: '/dashboard/products/$slug/edit'
      preLoaderRoute: typeof DashboardProductsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/partners/$id/edit': {
      id: '/dashboard/partners/$id/edit'
      path: '/partners/$id/edit'
      fullPath: '/dashboard/partners/$id/edit'
      preLoaderRoute: typeof DashboardPartnersIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery/$id/edit': {
      id: '/dashboard/gallery/$id/edit'
      path: '/gallery/$id/edit'
      fullPath: '/dashboard/gallery/$id/edit'
      preLoaderRoute: typeof DashboardGalleryIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/contact-us/$id/edit': {
      id: '/dashboard/contact-us/$id/edit'
      path: '/contact-us/$id/edit'
      fullPath: '/dashboard/contact-us/$id/edit'
      preLoaderRoute: typeof DashboardContactUsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/client-projects/$slug/edit': {
      id: '/dashboard/client-projects/$slug/edit'
      path: '/client-projects/$slug/edit'
      fullPath: '/dashboard/client-projects/$slug/edit'
      preLoaderRoute: typeof DashboardClientProjectsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-sectors/$slug/edit': {
      id: '/dashboard/business-sectors/$slug/edit'
      path: '/business-sectors/$slug/edit'
      fullPath: '/dashboard/business-sectors/$slug/edit'
      preLoaderRoute: typeof DashboardBusinessSectorsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs/$slug/edit': {
      id: '/dashboard/blogs/$slug/edit'
      path: '/blogs/$slug/edit'
      fullPath: '/dashboard/blogs/$slug/edit'
      preLoaderRoute: typeof DashboardBlogsSlugEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardBusinessSectorsCreateRoute: typeof DashboardBusinessSectorsCreateRoute
  DashboardGalleryCategoriesRoute: typeof DashboardGalleryCategoriesRoute
  DashboardServicesCreateRoute: typeof DashboardServicesCreateRoute
  DashboardBlogsCreateLazyRoute: typeof DashboardBlogsCreateLazyRoute
  DashboardClientProjectsCreateLazyRoute: typeof DashboardClientProjectsCreateLazyRoute
  DashboardContactUsCreateLazyRoute: typeof DashboardContactUsCreateLazyRoute
  DashboardGalleryCreateLazyRoute: typeof DashboardGalleryCreateLazyRoute
  DashboardPartnersCreateLazyRoute: typeof DashboardPartnersCreateLazyRoute
  DashboardProductsCreateLazyRoute: typeof DashboardProductsCreateLazyRoute
  DashboardTestimonialsCreateLazyRoute: typeof DashboardTestimonialsCreateLazyRoute
  DashboardUserManagementCreateLazyRoute: typeof DashboardUserManagementCreateLazyRoute
  DashboardVacanciesCreateLazyRoute: typeof DashboardVacanciesCreateLazyRoute
  DashboardBlogsIndexRoute: typeof DashboardBlogsIndexRoute
  DashboardBusinessSectorsIndexRoute: typeof DashboardBusinessSectorsIndexRoute
  DashboardGalleryIndexRoute: typeof DashboardGalleryIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
  DashboardServicesIndexRoute: typeof DashboardServicesIndexRoute
  DashboardVacanciesIndexRoute: typeof DashboardVacanciesIndexRoute
  DashboardClientProjectsIndexLazyRoute: typeof DashboardClientProjectsIndexLazyRoute
  DashboardContactUsIndexLazyRoute: typeof DashboardContactUsIndexLazyRoute
  DashboardFaqsIndexLazyRoute: typeof DashboardFaqsIndexLazyRoute
  DashboardOrganizationalStructureIndexLazyRoute: typeof DashboardOrganizationalStructureIndexLazyRoute
  DashboardPartnersIndexLazyRoute: typeof DashboardPartnersIndexLazyRoute
  DashboardSocialsIndexLazyRoute: typeof DashboardSocialsIndexLazyRoute
  DashboardTagsIndexLazyRoute: typeof DashboardTagsIndexLazyRoute
  DashboardTestimonialsIndexLazyRoute: typeof DashboardTestimonialsIndexLazyRoute
  DashboardUserManagementIndexLazyRoute: typeof DashboardUserManagementIndexLazyRoute
  DashboardBlogsSlugEditRoute: typeof DashboardBlogsSlugEditRoute
  DashboardBusinessSectorsSlugEditRoute: typeof DashboardBusinessSectorsSlugEditRoute
  DashboardClientProjectsSlugEditRoute: typeof DashboardClientProjectsSlugEditRoute
  DashboardContactUsIdEditRoute: typeof DashboardContactUsIdEditRoute
  DashboardGalleryIdEditRoute: typeof DashboardGalleryIdEditRoute
  DashboardPartnersIdEditRoute: typeof DashboardPartnersIdEditRoute
  DashboardProductsSlugEditRoute: typeof DashboardProductsSlugEditRoute
  DashboardServicesSlugEditRoute: typeof DashboardServicesSlugEditRoute
  DashboardTestimonialsIdEditRoute: typeof DashboardTestimonialsIdEditRoute
  DashboardUserManagementUserIdEditRoute: typeof DashboardUserManagementUserIdEditRoute
  DashboardVacanciesSlugApplicationsRoute: typeof DashboardVacanciesSlugApplicationsRoute
  DashboardVacanciesSlugEditRoute: typeof DashboardVacanciesSlugEditRoute
  DashboardBlogsSlugIndexRoute: typeof DashboardBlogsSlugIndexRoute
  DashboardBusinessSectorsSlugIndexRoute: typeof DashboardBusinessSectorsSlugIndexRoute
  DashboardClientProjectsSlugIndexRoute: typeof DashboardClientProjectsSlugIndexRoute
  DashboardContactUsIdIndexRoute: typeof DashboardContactUsIdIndexRoute
  DashboardGalleryIdIndexRoute: typeof DashboardGalleryIdIndexRoute
  DashboardPartnersIdIndexRoute: typeof DashboardPartnersIdIndexRoute
  DashboardProductsSlugIndexRoute: typeof DashboardProductsSlugIndexRoute
  DashboardServicesSlugIndexRoute: typeof DashboardServicesSlugIndexRoute
  DashboardTestimonialsIdIndexRoute: typeof DashboardTestimonialsIdIndexRoute
  DashboardUserManagementUserIdIndexRoute: typeof DashboardUserManagementUserIdIndexRoute
  DashboardVacanciesSlugIndexRoute: typeof DashboardVacanciesSlugIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardBusinessSectorsCreateRoute: DashboardBusinessSectorsCreateRoute,
  DashboardGalleryCategoriesRoute: DashboardGalleryCategoriesRoute,
  DashboardServicesCreateRoute: DashboardServicesCreateRoute,
  DashboardBlogsCreateLazyRoute: DashboardBlogsCreateLazyRoute,
  DashboardClientProjectsCreateLazyRoute:
    DashboardClientProjectsCreateLazyRoute,
  DashboardContactUsCreateLazyRoute: DashboardContactUsCreateLazyRoute,
  DashboardGalleryCreateLazyRoute: DashboardGalleryCreateLazyRoute,
  DashboardPartnersCreateLazyRoute: DashboardPartnersCreateLazyRoute,
  DashboardProductsCreateLazyRoute: DashboardProductsCreateLazyRoute,
  DashboardTestimonialsCreateLazyRoute: DashboardTestimonialsCreateLazyRoute,
  DashboardUserManagementCreateLazyRoute:
    DashboardUserManagementCreateLazyRoute,
  DashboardVacanciesCreateLazyRoute: DashboardVacanciesCreateLazyRoute,
  DashboardBlogsIndexRoute: DashboardBlogsIndexRoute,
  DashboardBusinessSectorsIndexRoute: DashboardBusinessSectorsIndexRoute,
  DashboardGalleryIndexRoute: DashboardGalleryIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
  DashboardServicesIndexRoute: DashboardServicesIndexRoute,
  DashboardVacanciesIndexRoute: DashboardVacanciesIndexRoute,
  DashboardClientProjectsIndexLazyRoute: DashboardClientProjectsIndexLazyRoute,
  DashboardContactUsIndexLazyRoute: DashboardContactUsIndexLazyRoute,
  DashboardFaqsIndexLazyRoute: DashboardFaqsIndexLazyRoute,
  DashboardOrganizationalStructureIndexLazyRoute:
    DashboardOrganizationalStructureIndexLazyRoute,
  DashboardPartnersIndexLazyRoute: DashboardPartnersIndexLazyRoute,
  DashboardSocialsIndexLazyRoute: DashboardSocialsIndexLazyRoute,
  DashboardTagsIndexLazyRoute: DashboardTagsIndexLazyRoute,
  DashboardTestimonialsIndexLazyRoute: DashboardTestimonialsIndexLazyRoute,
  DashboardUserManagementIndexLazyRoute: DashboardUserManagementIndexLazyRoute,
  DashboardBlogsSlugEditRoute: DashboardBlogsSlugEditRoute,
  DashboardBusinessSectorsSlugEditRoute: DashboardBusinessSectorsSlugEditRoute,
  DashboardClientProjectsSlugEditRoute: DashboardClientProjectsSlugEditRoute,
  DashboardContactUsIdEditRoute: DashboardContactUsIdEditRoute,
  DashboardGalleryIdEditRoute: DashboardGalleryIdEditRoute,
  DashboardPartnersIdEditRoute: DashboardPartnersIdEditRoute,
  DashboardProductsSlugEditRoute: DashboardProductsSlugEditRoute,
  DashboardServicesSlugEditRoute: DashboardServicesSlugEditRoute,
  DashboardTestimonialsIdEditRoute: DashboardTestimonialsIdEditRoute,
  DashboardUserManagementUserIdEditRoute:
    DashboardUserManagementUserIdEditRoute,
  DashboardVacanciesSlugApplicationsRoute:
    DashboardVacanciesSlugApplicationsRoute,
  DashboardVacanciesSlugEditRoute: DashboardVacanciesSlugEditRoute,
  DashboardBlogsSlugIndexRoute: DashboardBlogsSlugIndexRoute,
  DashboardBusinessSectorsSlugIndexRoute:
    DashboardBusinessSectorsSlugIndexRoute,
  DashboardClientProjectsSlugIndexRoute: DashboardClientProjectsSlugIndexRoute,
  DashboardContactUsIdIndexRoute: DashboardContactUsIdIndexRoute,
  DashboardGalleryIdIndexRoute: DashboardGalleryIdIndexRoute,
  DashboardPartnersIdIndexRoute: DashboardPartnersIdIndexRoute,
  DashboardProductsSlugIndexRoute: DashboardProductsSlugIndexRoute,
  DashboardServicesSlugIndexRoute: DashboardServicesSlugIndexRoute,
  DashboardTestimonialsIdIndexRoute: DashboardTestimonialsIdIndexRoute,
  DashboardUserManagementUserIdIndexRoute:
    DashboardUserManagementUserIdIndexRoute,
  DashboardVacanciesSlugIndexRoute: DashboardVacanciesSlugIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DemoRouteChildren {
  DemoAboutRoute: typeof DemoAboutRoute
  DemoContactRoute: typeof DemoContactRoute
  DemoScheduleRoute: typeof DemoScheduleRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoBlogsSlugRoute: typeof DemoBlogsSlugRoute
  DemoCareersSlugRoute: typeof DemoCareersSlugRoute
  DemoProjectsSlugRoute: typeof DemoProjectsSlugRoute
  DemoSectorsSlugRoute: typeof DemoSectorsSlugRoute
  DemoServicesSlugRoute: typeof DemoServicesSlugRoute
  DemoBlogsIndexRoute: typeof DemoBlogsIndexRoute
  DemoCareersIndexRoute: typeof DemoCareersIndexRoute
  DemoGalleryIndexRoute: typeof DemoGalleryIndexRoute
  DemoProjectsIndexRoute: typeof DemoProjectsIndexRoute
  DemoSectorsIndexRoute: typeof DemoSectorsIndexRoute
  DemoServicesIndexRoute: typeof DemoServicesIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAboutRoute: DemoAboutRoute,
  DemoContactRoute: DemoContactRoute,
  DemoScheduleRoute: DemoScheduleRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoBlogsSlugRoute: DemoBlogsSlugRoute,
  DemoCareersSlugRoute: DemoCareersSlugRoute,
  DemoProjectsSlugRoute: DemoProjectsSlugRoute,
  DemoSectorsSlugRoute: DemoSectorsSlugRoute,
  DemoServicesSlugRoute: DemoServicesSlugRoute,
  DemoBlogsIndexRoute: DemoBlogsIndexRoute,
  DemoCareersIndexRoute: DemoCareersIndexRoute,
  DemoGalleryIndexRoute: DemoGalleryIndexRoute,
  DemoProjectsIndexRoute: DemoProjectsIndexRoute,
  DemoSectorsIndexRoute: DemoSectorsIndexRoute,
  DemoServicesIndexRoute: DemoServicesIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  ForbiddenLazyRoute: ForbiddenLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RateLimitLazyRoute: RateLimitLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
